{
 "title": "Bike Stations",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Bike Stations",
   "type": "geomap",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "alias": "Datos",
     "groupBy": [
      { "params": [ "id::tag" ], "type": "tag" }
     ],
     "measurement": "mqtt_consumer",
     "query": "SELECT   last(\"bikes\"), \"latitude\", \"longitude\" FROM \"mqtt_consumer\" WHERE $timeFilter GROUP BY \"id\"::tag ",
     "select": [
      [
       { "params": [ "slots" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Evolucion Slots Y bicis Disponibles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "alias": "Slots libres",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mqtt_consumer",
     "query": "SELECT last(\"tSlots\") FROM \"mqtt_consumer\" WHERE (\"id\"::tag = 'totals') AND $timeFilter GROUP BY time($interval) fill(null) ORDER BY time DESC",
     "select": [
      [
       { "params": [ "tSlots" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "id::tag", "operator": "=", "value": "totals" }
     ]
    },
    {
     "alias": "Bicis Disponibles",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mqtt_consumer",
     "query": "SELECT last(\"tBikes\") FROM \"mqtt_consumer\" WHERE (\"id\"::tag = 'totals') AND $timeFilter GROUP BY time($__interval) fill(null) ORDER BY time DESC",
     "select": [
      [
       { "params": [ "tBikes" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "id::tag", "operator": "=", "value": "totals" }
     ]
    }
   ]
  },
  {
   "title": "Estado Actual",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Estaciones sin Bicis",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "mqtt_consumer",
     "query": "SELECT last(\"noBikes\") FROM \"mqtt_consumer\" WHERE (\"id\"::tag = 'totals') AND $timeFilter GROUP BY time(10s) ORDER BY time DESC",
     "select": [
      [
       { "params": [ "noBikes" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "id::tag", "operator": "=", "value": "totals" }
     ]
    },
    {
     "alias": "Estaciones sin Slots Disponibles",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mqtt_consumer",
     "query": "SELECT last(\"noSlots\") FROM \"mqtt_consumer\" WHERE (\"id\"::tag = 'totals') AND $timeFilter GROUP BY time($__interval) fill(null) ORDER BY time DESC",
     "select": [
      [
       { "params": [ "noSlots" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "id::tag", "operator": "=", "value": "totals" }
     ]
    }
   ]
  }
 ]
}