{
 "title": "Bike Stations",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Nuevos elementos",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 9, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "alias": "Nuevas Bicis disponibles",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mqtt_consumer",
     "select": [
      [
       { "params": [ "iAB" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "id::tag", "operator": "=", "value": "incidents" }
     ]
    },
    {
     "alias": "Nuevos Slots disponibles",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mqtt_consumer",
     "select": [
      [
       { "params": [ "iAS" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "id::tag", "operator": "=", "value": "incidents" }
     ]
    }
   ]
  },
  {
   "title": "Bike Stations",
   "type": "geomap",
   "gridPos": { "h": 17, "w": 15, "x": 9, "y": 0 },
   "targets": [
    {
     "alias": "Datos",
     "groupBy": [
      { "params": [ "id::tag" ], "type": "tag" }
     ],
     "measurement": "mqtt_consumer",
     "query": "SELECT   last(\"bikes\"), \"latitude\", \"longitude\" FROM \"mqtt_consumer\" WHERE $timeFilter GROUP BY \"id\"::tag ",
     "select": [
      [
       { "params": [ "slots" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Evolucion Slots Y bicis Disponibles",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 3 },
   "targets": [
    {
     "alias": "Slots libres",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mqtt_consumer",
     "query": "SELECT sum(\"slots\") FROM \"mqtt_consumer\" WHERE $timeFilter GROUP BY time($interval) fill(null) ORDER BY time DESC",
     "select": [
      [
       { "params": [ "AS" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "id::tag", "operator": "=", "value": "incidents" }
     ]
    },
    {
     "alias": "Bicis Disponibles",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mqtt_consumer",
     "select": [
      [
       { "params": [ "AB" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "id::tag", "operator": "=", "value": "incidents" }
     ]
    }
   ]
  },
  {
   "title": "Estaciones con Incidentes",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "alias": "Estaciones sin Bicis",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "mqtt_consumer",
     "query": "SELECT count(\"bikes\") FROM \"mqtt_consumer\" WHERE \"bikes\" = 0 AND $timeFilter GROUP BY  time($__interval) ORDER BY time DESC",
     "select": [
      [
       { "params": [ "bikes" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    },
    {
     "alias": "Estaciones sin Slots ",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mqtt_consumer",
     "query": "SELECT count(\"slots\") FROM \"mqtt_consumer\" WHERE $timeFilter AND \"slots\"=0 GROUP BY time($__interval) fill(null) ORDER BY time DESC",
     "select": [
      [
       { "params": [ "slots" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  }
 ]
}